Play travis
Otus-DevOps-2018-05/eogladkih_infra pull request #1
Opened 2018-06-14 19:40 UTC by eogladkih

Добавлена интеграция с Travis

2018-06-15 07:56 UTC, serjs requested changes
Привет!

По самому ДЗ - все ок, только у тебя в профиле Github не указаны Имя/Фамилия, я и другие преподаватели не сможем находить тебя в ведомости чтобы выставлять отметки по ДЗ + сейчас мне сложно найти твой канал в Slack с интеграцией.

Исправь профиль, пожалуйста.

2018-06-15 14:41 UTC, eogladkih commented
Добрый день!

В профиле гита указал имя и фамилию, канал в слаке #evgeny_gladkih

2018-06-16 06:11 UTC, eogladkih commented
Duplicate of #1 

Добрый день!

В профиле гита указал имя и фамилию, канал в слаке #evgeny_gladkih

2018-06-19 10:24 UTC, serjs approved these changes

2018-06-19 10:24 UTC, serjs commented
Теперь точно можно закрывать PR и мержить изменения в мастер ветку

2018-06-19 15:11 UTC, merged